title: Neslihan Kalayci
description: Cloud, AI & Digital Sovereignty Documentation
remote_theme: pmarsceill/just-the-docs
plugins:
  - jekyll-feed
  - jekyll-remote-theme
url: https://nkalayci.github.io
search_enabled: true
permalink: pretty
footer_content: "Â© 2026 Neslihan Kalayci"

# GitHub Pages settings
markdown: kramdown
highlighter: rouge
