title: Neslihan Kalayci
description: Cloud, AI & Digital Sovereignty Documentation
theme: minima
plugins:
  - jekyll-feed
url: https://nkalayci.github.io
search_enabled: true
nav_sort: case_insensitive
permalink: pretty
footer_content: "Â© 2026 Neslihan Kalayci"
heading_anchors: true
